### DISCUSSION TITLE
How to set extra Fonts 'Caskaydia Cove Nerd Font Complete'.

### DISCUSSION THREAD

**Discussion by neko3cs** [raphamorim/rio#518] [Q&A]
I wanna use 'Caskaydia Cove Nerd Font Complete', but I cannot it.
Can anyone help me how to set 'Caskaydia Cove Nerd Font Complete'?

That font I wanna set is able to downloaded from here.
🔗[Nerd Fonts - Iconic font aggregator, glyphs/icons collection, & fonts patcher](https://www.nerdfonts.com/font-downloads)

I try to set this, but it's not work.

Pattern 1:
```toml
[fonts]
family = "Caskaydia Cove Nerd Font Complete"
```

Pattern 2:
```toml
[fonts]
extras = [{ family = "Caskaydia Cove Nerd Font Complete" }]
```

Pattern 3:
```toml
[fonts.regular]
family = "Caskaydia Cove Nerd Font Complete"
style = "normal"
weight = 400

[fonts.bold]
family = "Caskaydia Cove Nerd Font Complete"
style = "normal"
weight = 800

[fonts.italic]
family = "Caskaydia Cove Nerd Font Complete"
style = "italic"
weight = 400

[fonts.bold-italic]
family = "Caskaydia Cove Nerd Font Complete"
style = "italic"
weight = 800
```

Versions:
<img width="763" alt="スクリーンショット 2024-06-03 0 20 00" src="https://github.com/raphamorim/rio/assets/36363130/ed61a247-e2f7-447c-a9b3-e4e31e274b2c">
