### DISCUSSION TITLE
Cross-Platform Configuation.

### DISCUSSION THREAD

**Discussion by neko3cs** [raphamorim/rio#522] [Ideas]
I wanna use zsh on macOS, but I wanna use pwsh on Windows.
However, to achieve this in Rio, two configuration files have to be maintained.

It would contribute more to the development of Rio if it were possible to support multiple environments in a configuration file, as follows.

````
# if no setting, use default
# [shell.macos]
# programme = ‘zsh’
# args = [‘--login’]

# if setting, use this setting
[shell.windows]
program = ‘pwsh’
args = [‘--login’]
```

**Comment by raphamorim** [comment]
That looks good as long it supports a default [shell] as well. Please feel free to reach me out in case you want to contribute

**Reply by neko3cs** [reply]
@raphamorim I want to contribute to Rio. 
But I am not good at Rust and I need time to contribute to Rio. 
Could you wait for my contact until I am ready to contribute?

**Comment by MrPandir** [comment]
There is one unclear point here:

Imagine that you have two Macs.
On your first Mac you use **bash** as your shell. And on the second **zsh**. How do you suggest configuring this? 🤔

**Reply by neko3cs** [reply]
@MrPandir  It's difficult problem.
One idea is to do the following. But it's not smart and would be a complex implementation..

```toml
[[shell.macos]]
hostname = 'neko3cs-MacBook-Pro'
program = 'zsh'
args = ['--login']

[[shell.macos]]
hostname = 'MrPandir-MacBook-Pro'
program = 'bash'
args = ['--login']
```
