### DISCUSSION TITLE
Does Rio not work well in Hyprland?

### DISCUSSION THREAD

**Discussion by stephanlamoureux** [raphamorim/rio#560] [Q&A]
I am using Arch/Hyprland, and my font will be set, but the font size won't work. The opacity will work, but the blur will not. The padding will also not work for x or y, among other things. 

I'm using a basic config:

```
editor = 'code'
cursor = '▇'
blinking-cursor = true
theme = "catppuccin-mocha"
padding-x = 10
padding-y = 10

[window]
foreground-opacity = 0.6
background-opacity = 0.6
blur = true
decorations = "Enabled"

[renderer]
performance = "High"
backend = "Automatic"
disable-renderer-when-unfocused = false

[fonts]
family = "IBM Plex Mono"
size = 16

[navigation]
mode = "BottomTab"
clickable = true
```

**Comment by Erikgavs** [comment]
The issue is that some keys are in the wrong place or have the wrong format.


**Font size** — `size` should be a float:
```toml
[fonts]
family = "IBM Plex Mono"
size = 16.0
```

**Padding** — doesn't go at the root level, it belongs inside `[window]`:
```toml
[window]
padding-x = 10
padding-y = 10
```

**Blur** — Rio's `blur = true` only works if Hyprland has blur enabled for that window. Add this to your `hyprland.conf`:
```ini
decoration {
    blur {
        enabled = true
        size = 8
        passes = 3
        new_optimizations = true
    }
}

windowrulev2 = opacity 0.6 0.6, class:^(rio)$
```
Without the `windowrulev2` opacity rule, the compositor won't treat the window as transparent and blur won't apply even if Rio requests it.

---

**Fixed config:**
```toml
editor = 'code'
cursor = '▇'
blinking-cursor = true
theme = "catppuccin-mocha"

[window]
padding-x = 10
padding-y = 10
foreground-opacity = 0.6
background-opacity = 0.6
blur = true
decorations = "Enabled"

[renderer]
performance = "High"
backend = "Automatic"
disable-renderer-when-unfocused = false

[fonts]
family = "IBM Plex Mono"
size = 16.0

[navigation]
mode = "BottomTab"
clickable = true
```

I use hyprland in arch, so if you have any questions, ask me
