### DISCUSSION TITLE
Rio config crate

### DISCUSSION THREAD

**Discussion by raphamorim** [raphamorim/rio#6] [Ideas]
~ Develop the configuration crate.

Path : https://github.com/raphamorim/rio/tree/main/config

## Description

The configuration should be the following paths otherwise Rio will use the default configuration.

- macOs path: `~/.rio/config.toml`

#### config.toml

```toml
# Rio configuration file

# <perfomance> Set WGPU rendering perfomance
# default: high
# options: high, average, low
perfomance = "high"

# <height> Set default height
# default: 400
height = 400

# <width> Set default width
# default: 600
width = 600

## TODO: Add more configs
```

This crate should be able to read and parse TOML file from a path based on a specific OS.

```rust
mod config;

#[tokio::main]
async fn main() -> Result<(), Box<dyn Error>> {
    let rio_config: config::Config = config::load().await.expect("Request Config");
    // doesn't need to implement Debug trait, this is just for the example here
    println!("{:?}", rio_config:);

```

Would be nice to have few tests as well ⭐
