### DISCUSSION TITLE
Alt as Option and Cursor blink have some issues

### DISCUSSION THREAD

**Discussion by FahimAnayet** [raphamorim/rio#673] [Q&A] [answered]
There is two problem bugging me. Now is it bug or my fault I've no idea. Need help 🥹

Firstly, option as alt has to be before cursor for some reason. And even so It uses both option key as Alt inside neovim (other terminal doesn't have this issue so no problem with neovim's config), works fine outside neovim and inside tmux > neovim though!

Secondly, cursor blinking makes rio super slow. Ugh!

Finally, there's also some issues with fonts (Doesn't render bold italic fonts 'Operator Mono' `echo -e "\033[1;3mBold Italic text\033[0m"` works on iTerm2 ) I'll post it later after testing more, And decoration buttonless doesn't remove button ribbon just button disappear, would be great if ribbon also removed. But still I love this terminal, It's like Alacritty but has ligatures <3

```toml
# this has to be before cursor otherwise this does not work if you enable cursor on macOS.
 option-as-alt = 'right'

# Cursor
 [cursor]
#
# Default cursor shape is 'block'
# Other available options are: 'underline', 'beam' or 'hidden'
#
 shape = 'beam'
#
# Whether the cursor blinks. The default is true
# If un-comment blinking rio becomes slow for some reason.
# blinking = true
```

**Comment by raphamorim** [comment, marked as answer]
Hey @FahimAnayet thanks for the issue! Yes, regarding the blinking cursor I am planning to fix on next release (related issue #663) and auto bolden as you mentioned as well (`echo -e "\033[1;3mBold Italic text\033[0m"` for Operator Mono, Fira Code and etecetera).

> Firstly, option as alt has to be before cursor for some reason. And even so It uses both option key as Alt inside neovim (other terminal doesn't have this issue so no problem with neovim's config), works fine outside neovim and inside tmux > neovim though!

By curiosity, if you use:

```toml
[keyboard]
use-kitty-keyboard-protocol = false
```

Does it works for you?
