### DISCUSSION TITLE
How to disable cursor blink when unfocus rio terminal

### DISCUSSION THREAD

**Discussion by huynguyeexn** [raphamorim/rio#771] [Q&A]
I have read the config cursor here https://raphamorim.io/rio/docs/config/cursor, but there are no instructions for disabling the cursor blink when unfocusing rio terminal. Can I do this or not?

**Comment by orhun** [comment]
This is currently not possible AFAIK. You can change the blinking configuration separately from the focused status. Would be a nice feature to add though.

**Comment by raphamorim** [comment]
Hey @huynguyeexn thanks for the discussion, is just about the blinking?

is possible to stop rendering if is unfocused

**Comment by huynguyeexn** [comment]
Thank for your answer, 

I would like only for cursor stop blinking, another still rendering.

And I tried set ```disable-unfocused-render = true```, but when I unfocus the cursor still blinking.

This is my config:
```toml
[cursor]
shape = 'block'
blinking = true
blinking-interval = 800

[renderer]
target-fps = 120
disable-unfocused-render = true

[fonts]
family = "FiraCode Nerd Font"
size = 13

[fonts.regular]
style = "Normal"
weight = 400

[fonts.bold]
style = "Normal"
weight = 800

[fonts.italic]
style = "Italic"
weight = 400

[fonts.bold-italic]
style = "Italic"
weight = 800

[colors]
background = '#272e33'
foreground = '#d3c6aa'
cursor = '#d699b6'
tabs = '#414b50'
tabs-active = '#F38BA3'
green = '#a7c080'
red = '#e67e80'
blue = '#7fbbb3'
yellow = '#dbbc7f'
```

I use MacBook Air M1, macOS Sequoia 15.1
