### ISSUE TITLE
[Feature Request] Add Option for “Default” Cursor Shape or Allow Applications to Change It

### ISSUE THREAD

**Issue by rsenna** [raphamorim/rio#1000]
Currently, Rio offers the following cursor (or "caret") shape options:

1. Block
2. Underline
3. Beam
4. Hidden

However, some CLI programs define their _own_ cursor shapes. For example, Fish shell 4 (in vi mode) can display a “beam” in insert mode or a “block” in normal mode. Rio does not respect these changes: it enforces the cursor shape set in config.toml, overriding any changes made by the running application.

This behaviour differs from terminal emulators like iTerm2, which allow the shell or application to modify the cursor shape dynamically.

By enforcing a fixed cursor style, Rio may be preventing shells and other applications from updating it as intended. This could also be related to issues such as [#918](https://github.com/raphamorim/rio/issues/918) and [#867](https://github.com/raphamorim/rio/issues/867), I suppose (just a hunch, I have not really looked into the code to know if that's the case.)

Would it be possible to either introduce a “default” cursor mode, that simply delegate to the running applications to control the cursor shape? Or "identify" if the cursor shape has been changed, and allow it...?

Thanks in advance.

**Comment by raphamorim** [comment]
Hey @rsenna thanks for the issue,

> However, some CLI programs define their own cursor shapes. For example, Fish shell 4 (in vi mode) can display a “beam” in insert mode or a “block” in normal mode. Rio does not respect these changes: it enforces the cursor shape set in config.toml, overriding any changes made by the running application.

Which CLI program are you talking about? (If isn't changing it's a bug)

Rio + nvim for me

<img width="369" alt="Image" src="https://github.com/user-attachments/assets/b9b3412f-da34-4af5-879e-1c4202287154" />

**Comment by rsenna** [comment]
It's on the shell itself - fish in this case (https://fishshell.com/), when you configure it to use vi mode.
I'm on macOS Sequoia 15.3.1 btw.


**On iTerm**

Insert mode:
![Image](https://github.com/user-attachments/assets/4d3ded78-f28f-4c34-8bb6-479c45f51dca)

Normal mode:
![Image](https://github.com/user-attachments/assets/8d4d026a-abce-4dfa-9aa0-a14ea7153afd)


**On Rio**

Insert mode:
![Image](https://github.com/user-attachments/assets/a4059668-1f0b-45e3-a1e3-56e909b7d1db)

Normal mode:
![Image](https://github.com/user-attachments/assets/1a0176e3-6c8c-4455-a188-b65674732ad8)


**Notes**

1. This is (most) of my rio/configs.toml file:

```toml
hide-cursor-when-typing = false

[cursor]
shape = 'block'
blinking = false
blinking-interval = 250

[window]
width = 2000
height = 1100
mode = "Fullscreen"
opacity = 0.2
blur = false
decorations = "Transparent"

[renderer]
performance = "low"
backend = "Metal"
disable-unfocused-render = true
level = 1
filters = [
  '/<redacted>/slang-shaders/crt/crt-consumer.slangp',
]

# [keyboard]
use-kitty-keyboard-protocol = true
# disable-ctlseqs-alt = false
# [fonts]
hinting = true

[navigation]
mode = "bookmark"
clickable = true
hide-if-single = true
use-current-path = false
color-automation = []

# MacOS with fish shell from homebrew:
[shell]
program = "/opt/homebrew/bin/fish"
args = ["--login"]
```

2. Parabéns pelo trabalho, o Rio é muito bom cara! 🇧🇷💪🏽
