### ISSUE TITLE
Binding Issue: Equivalent Shortcut to Open Floating Terminal in Rio

### ISSUE THREAD

**Issue by juniorsaldanha** [raphamorim/rio#1008]
Hi, I'm experiencing some difficulties with bindings in Rio. I've been using Alacritty for almost two years and really enjoy using a binding to open a floating terminal in vim. The usual shortcut I use is `Ctrl+/`. On Alacritty, I have a binding set up as shown below, but I couldn't figure out how to set an equivalent binding for Rio:

```toml
[keyboard]
bindings = [
  { key = "Slash", mods = "Control", chars = "\u001f" },
]
```

This Alacritty configuration binds the `Ctrl+/` shortcut to open a floating terminal. However, I'm having trouble finding an equivalent binding for Rio that achieves the same functionality. Can someone help me set up this binding in Rio?

**Comment by raphamorim** [comment]
Ctrl+/ now emits 0x1F out of the box (#1717 ships a test asserting exactly this), and custom byte sequences are supported via `esc =` bindings. Closing.

**Comment by juniorsaldanha** [comment]
Hi @raphamorim, I figured it out a while ago but forgot to come back and update this thread.

The config I've been using is:

```toml
[bindings]
keys = [
  { key = "/", with = "control", esc = "\u001f" }
]
```

I'll upgrade my Rio as soon as possible and test it out.
