### ISSUE TITLE
Shader Not Working with Metal Backend on macOS

### ISSUE THREAD

**Issue by Else00** [raphamorim/rio#1017]
#### **Issue Description**  
I am trying to use a shader in **Rio terminal** on **macOS**, but it does not work even after restarting Rio. According to the documentation, **only OpenGL is mentioned as not supporting shaders**, but there is no information on whether Metal supports them.  

#### **System Details**  
- **OS:** macOS 15.3.2 
- **Rio Backend:** `automatic` (which selects Metal)  
- **Rio Version:** rioterm 0.2.10

```bash
❯ file "/Users/else/Repos/slang-shaders/crt/shaders/newpixie/newpixie-crt.slang"
/Users/else/Repos/slang-shaders/crt/shaders/newpixie/newpixie-crt.slang: c program text, ASCII text
```

#### **Rio Configuration**  
```toml
[renderer]
filters = ["/Users/else/Repos/slang-shaders/crt/shaders/newpixie/newpixie-crt.slang"]
backend = "automatic"

[fonts]
family = "Hack Nerd Font"
```

#### **Steps Taken to Debug**  
1. Verified that the shader path is correct and exists (`ls -l` output confirmed it).  
2. Tried running Rio with `RIO_LOG=debug rio`, but no shader-related errors were displayed.  
3. Tried using **all backends**, and only **Metal and Automatic work**, but shaders still don’t apply.  
4. Since OpenGL was explicitly mentioned as **not supporting shaders**, I suspect that **Metal may also lack shader support**, but this is not stated in the documentation.  

#### **Questions**  
- Does **Metal** actually support filters/shaders in Rio?  
- If not, is there any plan to add support for Metal shaders in the future?
