### ISSUE TITLE
thin font and washed out colours

### ISSUE THREAD

**Issue by davidtwco** [raphamorim/rio#1054]
I use Rio on a MacBook Pro and MacBook Air with the same configuration and same font, everything works great on the MacBook Pro but not on my MacBook Air where the font is very thin (it's unclear if it is not finding the font or just rendering it wrong) and the colours are washed out.

![Image](https://github.com/user-attachments/assets/760e2f0d-b6bb-4984-a453-8d0f00bc9d5c)

Here's the config I use on both machines:

```toml
theme = "davidtwco"

confirm-before-quit = false

[editor]
program = "hx"

[window]
opacity = 0.95
blur = true
decorations = "transparent"
macos-use-shadow = true

[fonts]
size = 14

[fonts.regular]
family = "Iosevka Term"
style = "Normal"
weight = 400

[fonts.bold]
family = "Iosevka Term"
style = "Normal"
weight = 800

[fonts.italic]
family = "Iosevka Term"
style = "Italic"
weight = 400

[fonts.bold-italic]
family = "Iosevka Term"
style = "Italic"
weight = 800

[title]
content = ""

[navigation]
mode = "plain"
```

And here's the log when this happens on the MacBook Air, at `TRACE` level:

[rio.log](https://github.com/user-attachments/files/19719951/rio.log)
