### ISSUE TITLE
Pixelated powerline symbols after sugarloaf update

### ISSUE THREAD

**Issue by mahlquistj** [raphamorim/rio#1058]
After fixing [braille icons not rendering properly](https://github.com/raphamorim/rio/issues/1057#issuecomment-2801270772) (thanks btw 😄 ) i now experience pixelated powerline symbols from my Nerd Font.

![Image](https://github.com/user-attachments/assets/361b323a-55ad-4060-b696-2145be3d5ad3)

![Image](https://github.com/user-attachments/assets/fbecf737-c481-4176-9444-4fc77a7e4188)

After some digging, i found the new `fonts.use-drawable-chars` setting. Setting this to `false` removes the issue, but introduces two new ones:

Overlapping symbols (You can see the right-most powerline symbol in the purple section overlapping with the folder-icon, and the "-" symbol overlapping as well):
![Image](https://github.com/user-attachments/assets/10e9c32c-7f75-4cbd-b8dd-4aeee2921862)

Black bar on top, when zooming in completely:
![Image](https://github.com/user-attachments/assets/f39864bd-0abb-4919-bdcc-55c817575f16)

<details>
    <summary>My rio configuration</summary>

    ```toml
    confirm-before-quit = false
    hide-mouse-cursor-when-typing = true
    padding-x = 10
    padding-y = [10, 10]
    working-dir = "/home/maj"

    [colors]
    background = "#1e1e2e"
    black = "#45475a"
    blue = "#89b4fa"
    cursor = "#f5e0dc"
    cyan = "#94e2d5"
    dim-black = "#45475a"
    dim-blue = "#89b4fa"
    dim-cyan = "#94e2d5"
    dim-foreground = "#cdd6f4"
    dim-green = "#a6e3a1"
    dim-magenta = "#f5c2e7"
    dim-red = "#f38ba8"
    dim-white = "#bac2de"
    dim-yellow = "#f9e2af"
    foreground = "#cdd6f4"
    green = "#a6e3a1"
    light-black = "#585b70"
    light-blue = "#89b4fa"
    light-cyan = "#94e2d5"
    light-foreground = "#cdd6f4"
    light-green = "#a6e3a1"
    light-magenta = "#f5c2e7"
    light-red = "#f38ba8"
    light-white = "#a6adc8"
    light-yellow = "#f9e2af"
    magenta = "#f5c2e7"
    red = "#f38ba8"
    selection-background = "#f5e0dc"
    selection-foreground = "#1e1e2e"
    tabs = "#1e1e2e"
    tabs-active = "#b4befe"
    white = "#bac2de"
    yellow = "#f9e2af"
    
    [cursor]
    blinking = true
    shape = "block"
    
    [fonts]
    size = 18
    [fonts.bold]
    family = "SauceCodePro Nerd Font Mono"
    style = "Normal"
    weight = 800
    width = "Normal"

    [fonts.bold-italic]
    family = "SauceCodePro Nerd Font Mono"
    style = "Italic"
    weight = 800
    width = "Normal"
    
    [fonts.italic]
    family = "SauceCodePro Nerd Font Mono"
    style = "Italic"
    weight = 400
    width = "Normal"
    
    [fonts.regular]
    family = "SauceCodePro Nerd Font Mono"
    style = "Normal"
    weight = 400
    width = "Normal"
    
    [navigation]
    hide-if-single = true
    mode = "Bookmark"
    [[navigation.color-automation]]
    color = "#74c7ec"
    program = "nvim"
    
    [renderer]
    backend = "Automatic"
    performance = "High"
    
    [scroll]
    divider = 1
    multiplier = 1
    
    [shell]
    args = []
    program = "fish"

    [title]
    content = "{{ TITLE | PROGRAM }}"
    placeholder = "Rio"
    
    [window]
    blur = true
    decorations = "Disabled"
    opacity = 0.8
    ```
</details>
