### ISSUE TITLE
Unexpected font choices for some (emoji) characters

### ISSUE THREAD

**Issue by AndydeCleyre** [raphamorim/rio#1060]
Hello again!

With my fonts configured as:

```toml
[fonts]
size = 24
family = "Andysevka Term"
hinting = false
extras = [
  { family = "Symbols Nerd Font Mono" },
  { family = "Fluent Emoji Color" },
]
```

And the fonts listed being found [here](https://github.com/AndydeCleyre/archbuilder_iosevka/releases/download/andysevka-4.6/ttf-iosevka-term-custom-git-1743372721-1-any.pkg.tar.zst), [here](https://archlinux.org/packages/extra/any/ttf-nerd-fonts-symbols-mono/download/), and [here](https://github.com/tetunori/fluent-emoji-webfont/archive/refs/tags/v0.8.2.zip), here is the result of trying to print the string "🤷 😂 ❤️ 😍 🍻 🤰 " (`🤷 😂 ❤️ 😍 🍻 🤰 `) in each of Wezterm, Konsole, Ghostty, and Rio (that order, from top to bottom):

![Image](https://github.com/user-attachments/assets/33e53604-eaee-44cd-bd41-f3e0e6598544)

The configurations for the other terminals' fonts are as similar as I could make them.

It looks like Fluent Emoji Color isn't being used at all. Some of them are from OpenMoji, but I'm not sure about the others.

```console
$ fc-list | grep -i fluent
/usr/share/fonts/fluent-emoji/FluentEmojiFlat.ttf: Fluent Emoji Flat:style=Regular
/usr/share/fonts/fluent-emoji/FluentEmojiColor.ttf: Fluent Emoji Color:style=Regular
/usr/share/fonts/fluent-emoji/FluentEmojiHighContrast.ttf: Fluent Emoji High Contrast:style=Regular
```
