### ISSUE TITLE
poor active tab contrast

### ISSUE THREAD

**Issue by mcandre** [raphamorim/rio#1068]
Please visually differentiate the active terminal tab vs background tabs by tweaking the color (lighting). When opening many tabs, it is somewhat difficult to quickly see which of the many tabs is the active one.

**Comment by mcandre** [comment]
Tried enabling the demo tab contrast settings, but no effect.

```toml
[colors]
# background = '#0F0D0E'
# foreground = '#F9F4DA'
cursor = '#00FF00'
tabs = '#443d40'
tabs-active = '#F38BA3'
# green = '#0BA95B'
# red = '#ED203D'
# blue = '#12B5E5'
# yellow = '#FCBA28'
```

**Comment by mcandre** [comment]
Ah, there's a completely separate section to configure tab behavior:

```toml
[navigation]
mode = "toptab"
```
