### ISSUE TITLE
Text selection happens offset of mouse position

### ISSUE THREAD

**Issue by ararunaufc** [raphamorim/rio#1101]
This is somewhat similar to #573 and #535, but in my case the selection happens on the line below and is restricted to the lower lines.

https://github.com/user-attachments/assets/ab479327-eaf8-405d-bc6f-569696fbae91

I'm using version `0.2.15` from Arch.

My config contents are:

```toml
theme = "OneHalfLight"

padding-x = 5
padding-y = [0, 5]

line-height = 1.2

[editor]
program = "/usr/bin/env helix"

[window]
width = 800
height = 658

[fonts]
family = "JetBrainsMono Nerd Font"
size = 14

[navigation]
mode = "Plain"

[shell]
program = "zellij"
```

And I guess the custom `line-height` may be the culprit.
