### ISSUE TITLE
Font features doesn't work!?

### ISSUE THREAD

**Issue by znthvii** [raphamorim/rio#1125]
Hi.., I just tried this new terminal for my windows system, but font features doesn't work!

Windows 11
rioterm 0.2.16 (installed from winget)

My config ($Env.LOCALAPPDATA\rio\config.toml)
```toml
confirm-before-quit = false
shell = { program = "pwsh", args = [] }
working-dir = "/Users/<USERNAME>"

[renderer]
performance = "High"
backend = "Automatic"
disable-unfocused-render = false

[fonts]
family = "Fira Code"
features = ["cv01", "cv02"]
```

![Image](https://github.com/user-attachments/assets/e1cd4aeb-8d5b-4d11-ac2c-fd3273c9b55a)
![Image](https://github.com/user-attachments/assets/bc866b74-00f7-48fc-8b05-c8bfefb6dcab)

**Comment by sbradnick** [comment]
I'm noticing the same issue. I generally like to configure things via `~/.config/fontconfig/fonts.conf` (which doesn't apply to `rio`, but works in `kitty`/`ghostty` - and things like browsers and other system tools which respect fontconfig) and when I use these in `~/.config/rio/config.toml` it doesn't work:

```
[fonts]
size = 16
features = ["cv02", "ss02", "ss12", "ss13", "ss14", "zero"]
[fonts.emoji]
family = "Noto Color Emoji"
[fonts.regular]
family = "JuliaMono"
style = "Normal"
weight = 400
[fonts.bold]
family = "JuliaMono"
style = "Normal"
weight = 800
[fonts.italic]
family = "JuliaMono"
style = "Italic"
weight = 400
[fonts.bold-italic]
family = "JuliaMono"
style = "Italic"
weight = 800
```

**Comment by haetae-bit** [comment]
I'm also on Windows 11, using rio version 2.30.0 installed from scoop, and running into the same issue.

I tried uninstalling from scoop and installing from the installer from the Releases, but it's still not picking up the font features.

**Comment by testinfected** [comment]
I can confirm I have the same issue on Ubuntu. Trying to use ss01 for 0xProto font, nothing happens

**Comment by dminca** [comment]
Same issue on `macOS Tahoe 26.2`

I'm trying to set

```toml
["fonts.emoji"]
family = "Apple Color Emoji"

[["fonts.extras"]]
family = "JetBrainsMono Nerd Font"
```

but it doesn't render my font correctly

**Comment by sbradnick** [comment]
```toml
[fonts]
family = "JuliaMono"
features = ["cv02", "ss02", "ss12", "ss13", "ss14", "zero"]
```

was working up to v0.3.11 ; >= 0.4.0 and it's broken (as in ignored) again.
