### ISSUE TITLE
line-height adds small gaps for box-drawing characters

### ISSUE THREAD

**Issue by Skardyy** [raphamorim/rio#1126]
OS: windows
Version: rioterm 0.2.16

to reproduce:
```toml
line-height = 1.2

[fonts]
size = 28
family = "Cascadia Code NF"
use-drawable-chars = false
```
produces:
![Image](https://github.com/user-attachments/assets/71e89c6a-7299-4944-9c7d-d62a05990d04)

enabling `use-drawable-chars` seems to make it worse. see:
![Image](https://github.com/user-attachments/assets/65dc111a-a8cd-49a6-8c8a-d41c4a8a7073)
