### ISSUE TITLE
Blurry characters after update

### ISSUE THREAD

**Issue by mahlquistj** [raphamorim/rio#1168]
I recently updated to the latest release (v0.2.20) and i am now experiencing blurry text when using CAPS or cursive text.

![Image](https://github.com/user-attachments/assets/8bf98344-92d1-4e01-bc73-5ed7e86fce2a)

EDIT: This only happens on certain zoom-levels. I can get around it by applying a certain zoom level, which is not ideal, but works as a quick fix for me for now.

My config:
```
confirm-before-quit = false
hide-mouse-cursor-when-typing = true
padding-x = 10
padding-y = [10, 10]
working-dir = "/home/maj"

[colors]
background = "#1e1e2e"
black = "#45475a"
blue = "#89b4fa"
cursor = "#f5e0dc"
cyan = "#94e2d5"
dim-black = "#45475a"
dim-blue = "#89b4fa"
dim-cyan = "#94e2d5"
dim-foreground = "#cdd6f4"
dim-green = "#a6e3a1"
dim-magenta = "#f5c2e7"
dim-red = "#f38ba8"
dim-white = "#bac2de"
dim-yellow = "#f9e2af"
foreground = "#cdd6f4"
green = "#a6e3a1"
light-black = "#585b70"
light-blue = "#89b4fa"
light-cyan = "#94e2d5"
light-foreground = "#cdd6f4"
light-green = "#a6e3a1"
light-magenta = "#f5c2e7"
light-red = "#f38ba8"
light-white = "#a6adc8"
light-yellow = "#f9e2af"
magenta = "#f5c2e7"
red = "#f38ba8"
selection-background = "#f5e0dc"
selection-foreground = "#1e1e2e"
tabs = "#1e1e2e"
tabs-active = "#b4befe"
tabs-active-foreground = "#11111b"
tabs-active-highlight = "#b4befe"
tabs-foreground = "#cdd6f4"
white = "#bac2de"
yellow = "#f9e2af"

[cursor]
blinking = true
shape = "block"

[fonts]
size = 18

[fonts.bold]
family = "SauceCodePro Nerd Font Mono"
style = "Normal"
weight = 800
width = "Normal"

[fonts.bold-italic]
family = "SauceCodePro Nerd Font Mono"
style = "Italic"
weight = 800
width = "Normal"

[fonts.italic]
family = "SauceCodePro Nerd Font Mono"
style = "Italic"
weight = 400
width = "Normal"

[fonts.regular]
family = "SauceCodePro Nerd Font Mono"
style = "Normal"
weight = 400
width = "Normal"

[navigation]
hide-if-single = true
mode = "Bookmark"
[[navigation.color-automation]]
color = "#74c7ec"
program = "nvim"

[renderer]
backend = "Automatic"
performance = "High"

[scroll]
divider = 1
multiplier = 1

[shell]
args = []
program = "fish"

[title]
content = "{{ TITLE | PROGRAM }}"
placeholder = "Rio"

[window]
blur = true
decorations = "Disabled"
opacity = 0.8
```

**Comment by raphamorim** [comment]
Will take a look, the zoom and disappear it happens in main before 0.2.20 (need to fix it too). Does this blurriness happens on 0.2.19?

**Comment by sbradnick** [comment]
> Will take a look, the zoom and disappear it happens in main before 0.2.20 (need to fix it too). Does this blurriness happens on 0.2.19?

I rebuilt after a `git reset --hard 3245a162` and fonts (esp. italics) still look wonky, especially if I use a non-default config:

```toml
[fonts]
features = [
  "dlig",
  "ss01",
  "ss02",
  "ss03",
  "ss04",
  "ss05",
  "ss06",
  "ss07",
  "ss08",
]
size = 16

[fonts.regular]
family = "Cascadia Code NF"
style = "Normal"
weight = 400

[fonts.bold]
family = "Cascadia Code NF"
style = "Normal"
weight = 800

[fonts.italic]
family = "Cascadia Code NF"
style = "Italic"
weight = 400

[fonts.bold-italic]
family = "Cascadia Code NF"
style = "Italic"
weight = 800

[fonts.emoji]
family = "Noto Color Emoji"
```
