### ISSUE TITLE
Blur does not work on Windows

### ISSUE THREAD

**Issue by NSPC911** [raphamorim/rio#1174]
### Yes I did restart rio and my PC itself.
Config:
```toml
[window]
# width = 600
# height = 400
mode = "windowed"
opacity = 0
blur = true
decorations = "Transparent"
```

![Image](https://github.com/user-attachments/assets/601c9718-c282-441e-989d-2685eb22d72a)

The window titlebar isn't also transparent, which is a Windows limitation

However, if you force https://github.com/MicaForEveryone/MicaForEveryone to handle `rio`, you can make it and the titlebar blurred, but you have to set `blur` to `false` because for some reason, there's a double layered blur, which can cause there to be no blur at all

![Image](https://github.com/user-attachments/assets/f538ef3d-3f93-48d6-afb2-8474253cf404)

It is a workaround, but thought I'd leave this here
