### ISSUE TITLE
Delay in first run to open `rio` in Hyprland

### ISSUE THREAD

**Issue by AdsonCicilioti** [raphamorim/rio#1177]
I'm using Hyprland on Archlinux and I'm testing `rio` again as my default Terminal Emulator. I set it to open with the Super+Enter shortcut and when logging in and opening `rio` for the first time it takes about 3 to 5 seconds to open. After that the next calls are instantaneous.

What could it be? Something in my environment?

**Comment by raphamorim** [comment]
Hey @AdsonCicilioti thanks for the issue! Woof that's bad, do you have any configuration enabled? Also which version are you using?

**Comment by spikespaz** [comment]
My cold start time is longer than alacritty, but not that bad.

**Comment by agjini** [comment]
I've just switched from i3 to hyprland and noticed the same problem :
Each time I launch rio, the terminal window takes a little delay to open.

Opening alacrity takes no delay.

`rioterm 0.2.29`

My config.toml :


```toml
theme = "dracula"
option-as-alt = 'left'
confirm-before-quit = false

[cursor]
shape = 'block'
blinking = true
blinking-interval = 200

[editor]
program = "zed"
args = []

[window]
opacity = 0.8
blur = true

[fonts]
size = 18

[fonts.emoji]
family = "Noto Color Emoji"

[navigation]
mode = "Plain"

```

I'm able to reproduce also with no opacity and no blur.
