### ISSUE TITLE
Configure font for character ranges (symbol_map)

### ISSUE THREAD

**Issue by LiHRaM** [raphamorim/rio#124]
The kitty terminal has a very nice way of supporting powerline / alternative fonts without having to patch your current preferred font, which is the `symbol_map` feature.

Docs: https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.symbol_map

You can set any font as your default font for the terminal, and then you can define which symbols would be rendered using another font using the `symbol_map`. I would love to something like this in Rio.

**Comment by raphamorim** [comment]
I didn't even know about it, thank you very much for sharing @LiHRaM . For now I will move to wishlist to evaluate it later 👌

**Comment by raphamorim** [comment]
Connected: #135

Rio added a fallback for font icons as wezterm have, but would be nice to have the symbol map.

**Comment by hustcer** [comment]
How to configure the fallback fonts ? Thanks

> 
> Rio added a fallback for font icons as wezterm have

**Comment by raphamorim** [comment]
> How to configure the fallback fonts ? I want to add a fallback font for CJK characters. 
Thanks

```toml
[fonts]
extras = [{ family = "Microsoft JhengHei" }]
```

**Comment by hustcer** [comment]
> 
> @hustcer like this
> 
> ```toml
> [fonts]
> extras = [{ family = "Microsoft JhengHei" }]
> ```

Thanks, I have tried it the first time 0.0.22 was released, but it didn't work for me, my config:
```toml

cursor = '|'
blinking_cursor = true
performance = "High"
theme = "dracula"
ignore_theme_selection_fg_color = false
padding-x = 0
option-as-alt = 'both'

[window]
width = 1000
height = 600
opacity = 1.0
mode = "Windowed"

[fonts]
size = 26
extras = [
  { family = "PingFang SC" },
  { family = "Sarasa Gothic SC" },
]


[fonts.regular]
family = "Fira Code"
style = "normal"
weight = 400

[fonts.bold]
family = "Fira Code"
style = "normal"
weight = 800

[fonts.italic]
family = "Fira Code"
style = "italic"
weight = 400

[fonts.bold-italic]
family = "Fira Code"
style = "italic"
weight = 800
```
