### ISSUE TITLE
Add a way to change font weight (`Iosevka Term` causes really light unreadable text)

### ISSUE THREAD

**Issue by vbn** [raphamorim/rio#150]
OS: Windows 10
Rio version: 0.0.9 (portable)

the text is almost unreadable for the following config. i think it's due to the font weight being chosen is light. i guess 2 ways to solve this:
1. pick "regular" font weight for all fonts, not sure if there's an easy way that works for all fonts
2. allow config file to choose the font weight.

config:
```
font = "Iosevka Term"
font-size = 16

performance = "High"

shell = { program = "C:/Program Files/PowerShell/7/pwsh.exe", args = [] }
working_dir = "%USERPROFILE%"
```

![Screenshot 2023-07-17 114830](https://github.com/raphamorim/rio/assets/5567887/f98402b2-2c2c-413c-b9bf-6e128f2c8175)

**Comment by raphamorim** [comment]
Hey there @vbn, thanks for opening this issue.

I am working in a better font loader right now for Rio to next version, will include your issue on it. Is this the font https://github.com/be5invis/Iosevka ? (Asking in case want to test locally as well)

**Comment by vbn** [comment]
> I am working in a better font loader right now for Rio to next version, will include your issue on it. Is this the font https://github.com/be5invis/Iosevka ? (Asking in case want to test locally as well)

the font link is correct. awesome that you're already working on making this experience better.

excited to try rio again once the fixes make it to a release.

**Comment by raphamorim** [comment]
Added a new font api in 0.0.17

```toml
[fonts]
size = 18

[fonts.regular]
family = "cascadiamono"
style = "normal"
weight = 400

[fonts.bold]
family = "cascadiamono"
style = "normal"
weight = 800

[fonts.italic]
family = "cascadiamono"
style = "italic"
weight = 400

[fonts.bold-italic]
family = "cascadiamono"
style = "italic"
weight = 800
```
