### ISSUE TITLE
Tab bar overlaps text

### ISSUE THREAD

**Issue by filipebarros** [raphamorim/rio#167]
I'm not sure this is intended behaviour or if this is a bug though. 

Some of the configurations I am using:

```toml
font = "Hasklug Nerd Font Mono"
font-size = 14.0

padding-x = 10
```

<img width="1302" alt="image" src="https://github.com/raphamorim/rio/assets/748089/e5ba0e62-31e9-4c34-8763-89212f79953e">

On a different note, is there any plan to expand the existing custom keybinding actions to allow for something like `CMD` + `1` Switch to tab with index 1
