### ISSUE TITLE
Binding overwrite "ctrl + n" is not working in Manjaro Gnome

### ISSUE THREAD

**Issue by fdaciuk** [raphamorim/rio#171]
The command `Ctrl + N` opens a new window of Rio in Manjaro Gnome (probably the same in other OS, didn't check). I was trying to disable the command, but, for some reason, it is not working.

My config file (`~/.config/rio/config.toml`):

```toml
[bindings]
keys = [
  { key = "N", with = "control", action = "None" }
]
```

I tried `None` and `"None"` for `action`, `n` and `N` for `key`, but none is working.
