### ISSUE TITLE
`width` and `height` config seems doesn't work

### ISSUE THREAD

**Issue by hustcer** [raphamorim/rio#230]
The `width` and `height` config seems doesn't work for me, and change the values makes no difference:

```toml
[window]
width = 1000
height = 600
opacity = 1.0
mode = "Windowed"
```

Rio version: 0.0.18 (20230528.115631), MacOS
