### ISSUE TITLE
"Regression" in italics handling on v0.0.19

### ISSUE THREAD

**Issue by ralgozino** [raphamorim/rio#234]
On v0.0.18 I get proper italics for example for comments in VIM instead of just the font hinted (with `Victor Mono`).

Here's a screenshot with v0.0.18 on the left and v0.0.19 on the right, notice the difference in the comments' font rendering:
<img width="1792" alt="image" src="https://github.com/raphamorim/rio/assets/6362698/7b53e0e4-72db-426f-9c39-bcfa506624ba">

I'd prefer the behaviour that was on 0.0.18.

Here's my config in case is just a configuration issue:

```toml
blinking-cursor = true

[window]
width = 1200
height = 900

[fonts]
family = "Victor Mono"

[fonts.regular]
family = "Victor Mono"
style = "regular"
weight = 400

[fonts.bold]
family = "Victor Mono"
style = "bold"
weight = 800

[fonts.italic]
family = "Victor Mono"
style = "italic"
weight = 400

[fonts.bold-italic]
family = "Victor Mono"
style = "bold italic"
weight = 800

[navigation]
mode = "NativeTab"

[developer]
log-level = "INFO"
```
