### ISSUE TITLE
color-automation doen't work

### ISSUE THREAD

**Issue by BastienVigneron** [raphamorim/rio#251]
Despite my config file : 

```toml
[navigation]
mode = "Breadcrumb"
color-automation = [
  { program = "hx", color = "#FFFF00" }
]
```

The tab doesn't change color.

Version : rioterm 0.0.1
Os : Mac OS Ventura 13.5.2
