### ISSUE TITLE
config item `opacity` not work on win11

### ISSUE THREAD

**Issue by lost22git** [raphamorim/rio#268]
![Screenshot 2023-10-03 005123](https://github.com/raphamorim/rio/assets/65008815/8560d797-a3ba-4eb0-a8c3-ffbc7f4ec94b)

```toml
[background]
mode = "Color"
opacity = 0.5
```
