### ISSUE TITLE
Blinking cursor not working

### ISSUE THREAD

**Issue by leo-arch** [raphamorim/rio#309]
As the title says, setting `blinking-cursor` to `true` does not make any effect.

**Comment by raphamorim** [comment]
@leo-arch which platform are you using rio? is also the latest version?

**Comment by raphamorim** [comment]
(usually blinking-cursor requires rio restart)

**Comment by leo-arch** [comment]
Hi @raphamorim! Running on Arch, X window system, installed from the official repos (extra) version 0.0.24.

Restarting makes no difference.

**Comment by raphamorim** [comment]
Hmmm, just tested locally and it works for me. what's your configuration file?

**Comment by leo-arch** [comment]
```toml
blinking-cursor = true
performance = "High"
disable-unfocused-render = false
use-fork = true
use-kitty-keyboard-protocol = false
line-height = 1.0
theme = ""
padding-x = 0.0
cursor = "▇"
scroll-multiplier = 3.0
env-vars = []
option-as-alt = "false"
ignore-selection-foreground-color = false

[navigation]
mode = "CollapsedTab"
use-current-path = false

[window]
width = 600
height = 400
mode = "Windowed"

[background]

[shell]
program = ""
args = ["--login"]

[fonts]
#family = "Source Code Pro"
#size = 22.0
size = 20
extras = []

[fonts.regular]
family = "cascadiamono"
weight = 400
style = "normal"

[fonts.bold]
family = "cascadiamono"
weight = 800
style = "normal"

[fonts.bold-italic]
family = "Source Code Pro"
weight = 800
style = "italic"

[fonts.italic]
family = "cascadiamono"
weight = 400
style = "italic"

[developer]
enable-fps-counter = false
log-level = "OFF"

[bindings]
keys = []

[colors]
cursor = '#ffffff'
```
