### ISSUE TITLE
Window transparency does not work on X11

### ISSUE THREAD

**Issue by orhun** [raphamorim/rio#361]
Hello, I have the following config:

```toml
[window]
background-opacity = 0.1
```

Unfortunately window transparency does not work for me:

![cap](https://github.com/raphamorim/rio/assets/24392180/ed3848a7-d674-42a7-b07a-2578e9627f8e)

I'm using rio version `0.0.28` from Arch repos and i3 as window manager.
