### ISSUE TITLE
macOS: fonts blurry on non-HiDPI resolution

### ISSUE THREAD

**Issue by poegl** [raphamorim/rio#387]
On Mac OS X 14.2 Sonoma, on a non-HiDPI screen with 1440px vertical resolution, the fonts are blurry.

I tested it with two fonts, the “JetBrainsMonoNL Nerd Font” and the “Liga SFMono Nerd Font”.

In the image below on the left side you can see Alacritty and on the right side Rio, both displaying the content with the “JetBrainsMonoNL Nerd Font” on the same display, with slightly different font sizes.

![image](https://github.com/raphamorim/rio/assets/57896970/5f65dc83-0720-4bbe-bde1-c4a1d8978ff6)

**Comment by RaySlash** [comment]
Can u post the part of config where you set your fonts? You seem to have a Bold version on left and a normal/regular variant on right. I might be wrong. More info is best in this scenerio. Cheers!

**Comment by poegl** [comment]
Sure.

Here is the config of Rio:

```toml
theme = "dracula"

padding-x = 10

[fonts]
size = 15

[fonts.regular]
family = "JetBrainsMonoNL Nerd Font"
style = "normal"
weight = 600

[fonts.bold]
family = "JetBrainsMonoNL Nerd Font"
style = "normal"
weight = 800

[fonts.italic]
family = "JetBrainsMonoNL Nerd Font"
style = "italic"
weight = 600

[fonts.bold-italic]
family = "JetBrainsMonoNL Nerd Font"
style = "italic"
weight = 800

[navigation]
mode = "Breadcrumb"

[window]
foreground-opacity = 1.0
background-opacity = 0.9
macos-hide-toolbar-buttons = true
blur = true
```

Here is the font part of the Alacritty config:

```yaml
# Font configuration
font:
  # Normal (roman) font face
  normal:
    # Font family
    #
    # Default:
    #   - (macOS) Menlo
    #   - (Linux/BSD) monospace
    #   - (Windows) Consolas
    family: 'JetBrainsMonoNL Nerd Font'

    # The `style` can be specified to pick a specific face.
    style: Regular

  # Bold font face
  bold:
    # Font family
    #
    # If the bold family is not specified, it will fall back to the
    # value specified for the normal font.
    family: 'JetBrainsMonoNL Nerd Font'

    # The `style` can be specified to pick a specific face.
    style: Bold

  # Italic font face
  italic:
    # Font family
    #
    # If the italic family is not specified, it will fall back to the
    # value specified for the normal font.
    family: 'JetBrainsMonoNL Nerd Font'

    # The `style` can be specified to pick a specific face.
    style: Italic

  # Bold italic font face
  bold_italic:
    # Font family
    #
    # If the bold italic family is not specified, it will fall back to the
    # value specified for the normal font.
    family: 'JetBrainsMonoNL Nerd Font'

    # The `style` can be specified to pick a specific face.
    style: Bold Italic

  # Point size
  size: 11.0
```

**Comment by RaySlash** [comment]
Looking at the configs, I see you have different styles defined for each font faces in rio and alacritty. Could you use same styles and see if it still persists. Also, tweak the weight of the fontface to get that crispy bold look you are after. Good luck!

```toml
[fonts]
size = 15

[fonts.regular]
family = "JetBrainsMonoNL Nerd Font"
style = "Regular"
weight = 600        #update to to your liking

[fonts.bold]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold"
weight = 800

[fonts.italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Italic"
weight = 600

[fonts.bold-italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold Italic"
weight = 800
```

**Comment by poegl** [comment]
Hi, thanks for that Info. I updated it accordingly, but still not better and not that sharp as in Alacritty.

Here the outcome, on the left side again Alacritty and on the right Rio with exactly the same font settings, except the line height (couldn't figure out how to set it in Rio).

![Screenshot 2023-12-19 at 09 36 55](https://github.com/raphamorim/rio/assets/57896970/e1f8bb73-4947-4ee7-9482-cf89737b9e0d)

New font config Alacrity
```yaml
font:
  normal:
    family: 'JetBrainsMonoNL Nerd Font'
    style: SemiBold

  bold:
    family: 'JetBrainsMonoNL Nerd Font'
    style: Bold

  italic:
    family: 'JetBrainsMonoNL Nerd Font'
    style: SemiBold Italic

  bold_italic:
    family: 'JetBrainsMonoNL Nerd Font'
    style: Bold Italic

  size: 11.0
```

New font config Rio
```toml
[fonts]
size = 15

[fonts.regular]
family = "JetBrainsMonoNL Nerd Font"
style = "SemiBold"
weight = 600

[fonts.bold]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold"
weight = 800

[fonts.italic]
family = "JetBrainsMonoNL Nerd Font"
style = "SemiBold Italic"
weight = 600

[fonts.bold-italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold Italic"
weight = 800
```
