### ISSUE TITLE
Add support for Leader key when configuring bindings

### ISSUE THREAD

**Issue by benbooth493** [raphamorim/rio#415]
Similar to Wezterm it would be good to support a Leader key.
This would allow the emulation of tmux behaviour when using native window and pane management.

**Comment by raphamorim** [comment]
Hey there! thanks for the issue @benbooth493 , I think it's a good idea and might be a good issue for beginners. Marking as wishlist and good for beginners.

**Comment by orhun** [comment]
I will give this one a shot, can you assign it to me?

**Comment by raphamorim** [comment]
will do right now 👌

**Comment by orhun** [comment]
Based on [Wezterm's leader key](https://wezfurlong.org/wezterm/config/keys.html#leader-key) configuration, I'm thinking of something like:

```toml
[bindings]
leader = { key = "b", with = "control" }
keys = [
  { key = "c", with = "leader", action = "createtab" },
]
```

Thoughts?
