### ISSUE TITLE
[Bug] Paste is pasting twice

### ISSUE THREAD

**Issue by gplusplus314** [raphamorim/rio#419]
When pasting text into Rio, the text is pasted twice.

## Reproduction:
1. Copy any text from anywhere, including Rio itself.
2. Paste it into Rio

## My environment:
OS: Windows 11 Pro 23H2, 22631.3007
Rio version: rel [v0.0.34](https://github.com/raphamorim/rio/releases/tag/v0.0.34)

## entire config:
<details><summary>config.toml</summary>
<p>

```toml
cursor = '▇'
blinking-cursor = false

ignore_theme_selection_fg_color = false

performance = "High"

[window]
decorations = "Disabled"

[fonts]
family = "SauceCodePro Nerd Font"
size = 20
[fonts.regular]
weight = 400
[fonts.bold]
weight = 600
[fonts.italic]
weight = 400
[fonts.bold-italic]
weight = 600

[navigation]
mode = "BottomTab"
clickable = true
use-current-path = true
# color-automation = []
# macos-hide-window-buttons = true

[shell]
program = "nu.exe"
args = []

[colors]
tabs = '#111111'
tabs-active = '#5500AA'
cursor = '#00DD00'
selection-foreground = '#000000'
selection-background = '#AAAA00'

[bindings]
keys = [
	# Disable most defaults
	{ key = ",", with = "control | shift", action = "ReceiveChar" },
	{ key = "space", with = "alt | shift", action = "ReceiveChar" },
	{ key = "n", with = "control | shift", action = "ReceiveChar" },
	{ key = "t", with = "control | shift", action = "ReceiveChar" },
	{ key = "tab", with = "control", action = "ReceiveChar" },
	{ key = "]", with = "control | shift", action = "ReceiveChar" },
	{ key = "tab", with = "control | shift", action = "ReceiveChar" },
	{ key = "[", with = "control | shift", action = "ReceiveChar" },
	{ key = "0", with = "control", action = "ReceiveChar" },
	{ key = "w", with = "control | shift", action = "ReceiveChar" },

	# Keybinds I actually want
	{ key = "c", with = "control | shift", action = "Copy" },
	{ key = "v", with = "control | shift", action = "Paste" },
	{ key = "=", with = "control", action = "IncreaseFontSize" },
	{ key = "-", with = "control", action = "DecreaseFontSize" },
	{ key = "n", with = "alt | shift", action = "CreateWindow" },
	{ key = "t", with = "alt", action = "CreateTab" },
	{ key = "1", with = "alt", action = "SelectTab(0)" },
	{ key = "2", with = "alt", action = "SelectTab(1)" },
	{ key = "3", with = "alt", action = "SelectTab(2)" },
	{ key = "4", with = "alt", action = "SelectTab(3)" },
	{ key = "5", with = "alt", action = "SelectTab(4)" },
	{ key = "6", with = "alt", action = "SelectTab(5)" },
	{ key = "7", with = "alt", action = "SelectTab(6)" },
	{ key = "8", with = "alt", action = "SelectTab(7)" },
	{ key = "9", with = "alt", action = "SelectTab(8)" },
	{ key = "0", with = "alt", action = "SelectTab(9)" },
	{ key = "pageup", with = "alt", action = "ScrollHalfPageUp" },
	{ key = "pagedown", with = "alt", action = "ScrollHalfPageDown" },
]
```

</p>
</details>
