### ISSUE TITLE
specification to Rio themes (folder pattern)

### ISSUE THREAD

**Issue by avelino** [raphamorim/rio#42]
We need to support external themes (users get to develop a known theme, this accelerates adoption of Rio).

Today we have to put the theme configuration in `~/.rio/config.toml` making it impossible to create and distribute known themes.

## solution

When setting the theme name in Rio config:

```toml
[style]
theme = "Basic"
```

We can see if the file `~/.rio/themes/basic.toml` exists, if so, load the theme file and merge it with the config file `~/.rio/config.toml`.

Example: `~/.rio/themes/monotropic-coffee.toml`
```toml
# monotropic coffee
[colors]
background = "#fffffa"
foreground = "#593e2c"
cyan = "#593e2c"
green = "#745b4b"
red = "#593e2c"
magenta = "#593e2c"
yellow = "#c6bab3"
```
