### ISSUE TITLE
Glyphs have very weird rendering

### ISSUE THREAD

**Issue by yavko** [raphamorim/rio#476]
A lot of the time characters are just hidden, like here in the helix editor
![image](https://github.com/raphamorim/rio/assets/15178513/f80bd3ed-1de6-4bdd-81e7-a92d611c0b70)
a lot of my prompt is hidden
![image](https://github.com/raphamorim/rio/assets/15178513/b750b9de-2a33-424f-851f-f1bceac5feca)
but if i highlight it i can see it kinda
![image](https://github.com/raphamorim/rio/assets/15178513/c494855e-482c-42f6-8559-60a0dbad82d0)
in helix moving my cursor over some glyphs shows more of the current line
![image](https://github.com/raphamorim/rio/assets/15178513/861d4064-fe08-4cdd-946c-d1212ca56a23)

i honestly have no clue why this is happening, here is my config (was happening w/ empty config too)
```toml
shell = { program = "pwsh", args = ["--login"] }

cursor = '|'
[colors]

# Normal colors
foreground       = '#CDD6F4'
background       = '#1E1E2E'
black            = '#45475A'
blue             = '#89B4FA'
cursor           = '#F5E0DC'
cyan             = '#94E2D5'
green            = '#A6E3A1'
magenta          = '#F5C2E7'
red              = '#f38ba8'
white            = '#BAC2DE'
yellow           = '#F9E2AF'

# UI colors
tabs             = '#1E1E2E'
tabs-active      = '#B4BEFE'
selection-foreground = '#1E1E2E'
selection-background = '#F5E0DC'

# Dim colors
dim-black        = '#45475A'
dim-blue         = '#89B4FA'
dim-cyan         = '#94E2D5'
dim-foreground   = '#CDD6F4'
dim-green        = '#A6E3A1'
dim-magenta      = '#F5C2E7'
dim-red          = '#F38BA8'
dim-white        = '#BAC2DE'
dim-yellow       = '#F9E2AF'

# Light colors
light-black      = '#585B70'
light-blue       = '#89B4FA'
light-cyan       = '#94E2D5'
light-foreground = '#CDD6F4'
light-green      = '#A6E3A1'
light-magenta    = '#F5C2E7'
light-red        = '#F38BA8'
light-white      = '#A6ADC8'
light-yellow     = '#F9E2AF'


[fonts]
family = "VictorMono Nerd Font"
size = 13


[renderer]
performance = "High"
backend = "DX12"
disable-unfocused-render = false
```

here is also the brokenly rendered choco info text (i also tried w/ the msi installer, it also happens on the latest version)
![image](https://github.com/raphamorim/rio/assets/15178513/4bada1cb-2199-4dde-86ca-5b61113a75f4)
