### ISSUE TITLE
[Bug] Noticeable text update

### ISSUE THREAD

**Issue by MrPandir** [raphamorim/rio#492]
When I enter `docker stats` I see the text update every second and the cursor momentarily jumps to the beginning.
This does not happen in `Apple Terminal`.
But this does not happen with programs that refresh the entire screen such as `btop` or `htop` and are displayed correctly.

# Videos

https://github.com/raphamorim/rio/assets/137798474/230e12a5-cf14-4149-ab01-08990e7e7450

https://github.com/raphamorim/rio/assets/137798474/7005102f-51a9-4284-a99f-9c2f2c38a410

# Additional Information
Rio Version: `0.0.36`
OS: `macOS 14.4`
Config:
```toml
cursor = '▇'
blinking-cursor = false
confirm-before-quit = false
[navigation]
mode = "CollapsedTab"
```
