### ISSUE TITLE
[Bug] Tab indicator doesn't disappear

### ISSUE THREAD

**Issue by MrPandir** [raphamorim/rio#493]
If you delete the first tab, the terminal automatically switches to the second tab, but the tab indicators are not updated.
If you create a new tab and delete it (it will be the second one), the tab indicators will disappear. I expect the same behavior when deleting the first tab.

# Video

https://github.com/raphamorim/rio/assets/137798474/0c60720e-6253-45b7-917b-511ac36e34b8

# Additional Information
Rio Version: `0.0.36`
OS: `macOS 14.4`
Config:
```toml
cursor = '▇'
blinking-cursor = false
confirm-before-quit = false
[navigation]
mode = "CollapsedTab"
```
