### ISSUE TITLE
[Bug] The `[colors]` option does not override theme colors.

### ISSUE THREAD

**Issue by MrPandir** [raphamorim/rio#494]
As the documentation states:
> Defining colors in the configuration file will override any colors set in the theme if you're using a theme.

The background should be white as specified by `background = '#FFFFFF'`

# Screenshots

<img width="628" alt="Screenshot 2024-04-24 at 16 19 40" src="https://github.com/raphamorim/rio/assets/137798474/748bf50b-9d9e-4237-9aa6-60c5d79413b1">

# Additional Information
Rio Version: `0.0.36`
OS: `macOS 14.4`
Config:
```toml
theme = "Dark Pastel"
confirm-before-quit = false
[navigation]
mode = "CollapsedTab"
[colors]
background = '#FFFFFF'
```
