### ISSUE TITLE
[Feature] Add support for choosing font width

### ISSUE THREAD

**Issue by MrPandir** [raphamorim/rio#507]
For example, a font like [Iosevka](https://typeof.net/Iosevka/) provides 2 widths: `Normal` and `Extended`. And if you use [customization](https://typeof.net/Iosevka/customizer), then it is available 7 widths: `416`, `456`, `500`, `548`, `600`, `658`, `720`

Demonstration of what it affects:
<a href="https://www.theinformedillustrator.com/2013/10/typography-for-illustrators-6.html"><img src="https://github.com/raphamorim/rio/assets/137798474/61f3e089-9646-497b-b861-aa99c9b2be8a" width="50%"></a>

And here is more information: [MDN font-stretch](https://developer.mozilla.org/en-US/docs/Web/CSS/font-stretch#values)

You will need to add the `width` parameter to the configuration file:
```toml
[fonts]
family = "Iosevka Custom"
width = 600
```
You may also need to provide a text version:
```toml
[fonts]
family = "Iosevka Custom"
width = "Extended"
```
