### ISSUE TITLE
Odd background transparency on macOS (Intel)

### ISSUE THREAD

**Issue by grantholle** [raphamorim/rio#514]
![Screenshot 2024-05-24 at 8 45 15 AM](https://github.com/raphamorim/rio/assets/1189456/b492e108-cc2a-443d-81fe-7887bca3b22f)

The background doesn't span the entire window, leaving it hard to know where the window actually is since it's transparent. Here's my config:

```toml
editor = 'code'
line-height = 1.2
cursor='|'
padding-x = 15
working_dir = "/Users/grant"

[window]
foreground-opacity = 1.0
background-opacity = 0.8

[fonts]
size = 18
family='JetBrains Mono'
```

I can fix the issue by setting `background-opacity = 1.0`, quitting and restarting. However, as soon as I add any other value for `background-opacity`, the issue reoccurs.
