### ISSUE TITLE
Can't `SelectPrevTab` in breadcrumb navigation mode

### ISSUE THREAD

**Issue by boringplay** [raphamorim/rio#547]
`cmd+shift+[` doesn't select prev tab in breadcrumb navigation mode. Even if I add specific key bindings, it still doesn't work
```toml
[navigation]
mode = "Breadcrumb"
clickable = true

[bindings]
keys = [
    { key = "[", with = "super | shift", action = "SelectPrevTab" },
    { key = "]", with = "super | shift", action = "SelectNextTab" },
]
```

Mac OS
