### ISSUE TITLE
[Bug] glyphs have a right shift

### ISSUE THREAD

**Issue by MrPandir** [raphamorim/rio#581]
This is tested on the nightly build (with the latest commit 6bfbb2c).
<img width="1512" src="https://github.com/user-attachments/assets/85ccb01b-2a58-4070-b50e-cf3d0f86c39b">
This is how it should look, using Alacrity as an example:
<img width="912" src="https://github.com/user-attachments/assets/0960c3d2-570a-484f-be88-2c38201dc3cd">

**Comment by raphamorim** [comment]
Very interesting, this I cannot reproduce

<img width="457" alt="Screenshot 2024-08-08 at 13 25 43" src="https://github.com/user-attachments/assets/ef5603c4-4a07-4c9a-89cb-a28151a89b69">
<img width="239" alt="Screenshot 2024-08-08 at 13 25 50" src="https://github.com/user-attachments/assets/07fadf57-308e-4f2d-88ae-1dbe8849069c">

are you using a specific font family or the default?

**Comment by MrPandir** [comment]
Yes, I use a different font [Iosevka](https://typeof.net/Iosevka/).
I think this may be due to the fact that my font has a width of 600. But regular fonts use 500.
I described this in detail in #507.

```toml
[fonts]
size = 18

[fonts.regular]
family = "Iosevka Custom"
style = "normal"
# weight = 600

[fonts.bold]
family = "Iosevka Custom"
style = "normal"
# weight = 900

[fonts.italic]
family = "Iosevka Custom"
style = "italic"
# # weight = 600

[fonts.bold-italic]
family = "Iosevka Custom"
style = "italic"
# weight = 800
```
