### ISSUE TITLE
[Bug]: some parts of fonts are not renderd correcly

### ISSUE THREAD

**Issue by timon-schelling** [raphamorim/rio#583]
Some parts of my font are now broken with d86ec56ab17629d4add2f75c50d8e676f7e9d0c4.

In this video on the left d86ec56ab17629d4add2f75c50d8e676f7e9d0c4 on the right v0.0.39:

https://github.com/user-attachments/assets/9b76e413-3db3-4302-b528-e25edfd7b62c

Environment of both processes is identical. Did font loading change in some way?

Font related config:

```toml
[fonts]
family = "JetBrainsMono Nerd Font"
size = 24

[fonts.regular]
weight = 600
```

**Comment by timon-schelling** [comment]
Yes Linux (NixOS)

**Comment by raphamorim** [comment]
Yea, the issue is similar to a problem we discussed on Discord. Rio doesn't add or load symbols/unicode on linux. We have been discussing the best way to address this issue, an idea would be the package manager install the font for you and Rio just loads it.

But for your case you can simply add on your configuration file

```toml
[fonts]
extras = [{ family = "The name of the symbol font installed" }]
```
