### ISSUE TITLE
Setting `theme` stopped working since version `0.1.7`

### ISSUE THREAD

**Issue by MrPandir** [raphamorim/rio#601]
Instead of the installed theme, default colors are used. This was broken in version https://github.com/raphamorim/rio/releases/tag/v0.1.7.

For example, take the theme:
https://github.com/raphamorim/rio-terminal-themes/blob/d164b8c4a11e66a496235968fa806c8478caeedf/themes/Dark%20Pastel.toml

The cursor color should be **gray**, but it is **purple**, which is the default color.

Also here is [my config](https://gist.github.com/MrPandir/3e3149a3bd8f843c2660507846ce85f4), but I think it is an easily reproducible issue and you won't need it. 😄

**Comment by renegadespork** [comment]
I believe I discovered the cause for this one and an easy workaround.

I noticed the format for the "Editor" section changed from 
```toml
editor = "vi"
```
to
```toml
[editor]
program = "vi"
args = []
```
This broke all the config settings until the next `[header]` including cursor, blinking-cursor, and theme. Since these parameters don't have a header section I'm aware of, you can fix this issue my moving the editor section after the "headerless" parameters. 

Here's an example:
```toml
# Cursor
#
# Default cursor is Block
# Other available options are: '_' and '|'
#
cursor = '_'

# Blinking Cursor
#
# Default is true
#
blinking-cursor = true

# Hide the cursor while typing
#
# Default is `false`
#
# hide-cursor-when-typing = false

# Ignore theme selection foreground color
#
# Default is false
#
# Example:
# ignore-selection-foreground-color = false

# Theme
#
# It makes Rio look for the specified theme in the themes folder
# (macos and linux: ~/.config/rio/themes/dracula.toml)
# (windows: C:\Users\USER\AppData\Local\rio\themes\dracula.toml)
#
# Example:
theme = "tokyonight"

# Padding-x
#
# define x axis padding (default is 0)
#
# Example:
# padding-x = 10

# Option as Alt
#
# This config only works on MacOS.
# Possible choices: 'both', 'left' and 'right'.
#
# Example:
# option-as-alt = 'left'

# Line height
#
# This option will apply an modifier to line-height
# Default is `1.0`
#
# Example:
# line-height = 1.2

# Startup directory
#
# Directory the shell is started in. If this is unset the working
# directory of the parent process will be used.
#
# This configuration only has effect if use-fork is disabled.
#
# Example:
# working-dir = "/Users/raphael/Documents/"

# Environment variables
#
# Example:
# env-vars = []

# Use fork
#
# Defaults for POSIX-based systems (Windows is not configurable):
# MacOS: spawn processes
# Linux/BSD: fork processes
#
# Example:
# use-fork = false

# Confirm before exiting Rio
# Default is `true`
#
# confirm-before-quit = false

# Editor
#
# Default editor is "vi".
#
# Whenever the key binding `OpenConfigEditor` is triggered it will
# use the value of the editor along with the rio configuration path.
[editor]
program = "micro"
args = []

# Window configuration
...
```
You only encounter this if you've uncommented the editor configuration, which is commented by default. This is probably why the issue was missed. 

Either the default config should reorder these parameters, or these other settings should get their own headers.

**Comment by MrPandir** [comment]
Thanks for the help, I didn't even think about it.

I think it's worth showing an error if an unknown key is found.
For example:
```toml
[editor]
program = "vi"
args = []

cursor = '_'
```
And show probable fixes if such a key exists, but it requires a different header.
Something like:
_Parameter `cursor` received an unexpected header `[editor]`. You should use this parameter without a header._

And also make a change to the default configuration, in which move the `[editor]` section after all headerless parameters.
