### ISSUE TITLE
v0.1.12 still shows as v0.1.11

### ISSUE THREAD

**Issue by necromeo** [raphamorim/rio#653]
Smallish issue.
The version number hasn't been bumped up for v0.1.12 in the `Cargo.toml`.
```toml
[workspace.package]
version = "0.1.11"
```
