### ISSUE TITLE
Adaptive theme doesn't appear to work correctly on macOS

### ISSUE THREAD

**Issue by elijahblackmore** [raphamorim/rio#660]
I seem to be getting incorrect behaviour when using the adaptive theme feature. I have two valid [Catppuccin](https://github.com/catppuccin/rio) themes placed in the `themes` directory at `~/.config/rio`.

In my `config.toml`, I have added the following block:

```toml
[adaptive-theme]
light = "catppuccin-latte"
dark = "catppuccin-frappe"
```

Changing my system theme doesn't reflect the smooth transition like the  [example provided](https://raphamorim.io/rio/docs/features/adaptive-theme), nor does it update the theme until the config is reloaded.

I am on macOS Sonoma 14.6.1 and rioterm 0.1.12.
