### ISSUE TITLE
Opacity settings not working with background image

### ISSUE THREAD

**Issue by necromeo** [raphamorim/rio#715]
When setting a background image, opacity is not behaving as expected.
Reference image and settings below.

System information:
- Linux pop-os 6.9.3-76060903-generic #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S x86_64 x86_64 x86_64 GNU/Linux
---
```toml
[window]
opacity = 0.8

[window.background-image]
path = "/.../retro_space.png"
opacity = 0.8
```
![Screenshot from 2024-10-16 16-18-06](https://github.com/user-attachments/assets/ea9433b3-5af8-41b1-a888-4ff225230c5a)
