### ISSUE TITLE
Multiplatform configuration

### ISSUE THREAD

**Issue by raphamorim** [raphamorim/rio#755]
Currently Rio has no way to have different shell, window and navigation per OS.

So, we should introduce a new property called `platform`, that allow overwrite per OS.

This new property will allow users to configure on demand

```toml
[shell]
# default (in this case will be used only on MacOS)
program = "/bin/fish"
args = ["--login"]

[platform]
# Microsoft Windows overwrite
windows.shell.program = "pwsh"
windows.shell.args = ["-l"]

# Linux overwrite
linux.shell.program = "tmux"
linux.shell.args = ["new-session", "-c", "/var/www"]
```
