### ISSUE TITLE
runtime error after changing to a specific retroarch shader on windows

### ISSUE THREAD

**Issue by ddanielsantos** [raphamorim/rio#788]
rio version: 0.2.0
installation method: cargo
os: windows 11 pro - 23H2

```toml
# config.toml
shell = { program = "pwsh", args = ["--login"] }

[fonts]
family = "Iosevka Nerd Font Mono"
size = 17

[editor]
program = "hx"
args = []

[renderer]
# strategy = "Continuous"
filters = [
  "C:/Users/rsant/AppData/Local/rio/slang-shaders/motionblur/mix_frames.slangp" # https://github.com/libretro/slang-shaders/blob/master/motionblur/mix_frames.slangp
]
```

```
 panicked at C:\Users\rsant\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-23.0.0\src\backend\wgpu_core.rs:999:18:
wgpu error: Validation Error

Caused by:
  In Device::create_bind_group, label = 'main bind group'
    Number of bindings in bind group descriptor (2) does not match the number of bindings defined in the bind group layout (3)


panicked at C:\Users\rsant\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-hal-23.0.0\src\vulkan\instance.rs:173:58:
Trying to destroy a SurfaceSemaphores that is still in use by a SurfaceTexture
```

other shaders seens to work
