### ISSUE TITLE
Cannot spawn a new process with shell option

### ISSUE THREAD

**Issue by kaankoken** [raphamorim/rio#796]
Hi there, 

I recently started to use `rio` (it is great btw).  The `shell` option cannot spawn a new process.

```toml
[shell]
args = ['--login']
program = '/bin/zsh'

# or
[shell]
program = "/opt/homebrew/bin/tmux"
args = ["new-session", "-c", "/var/www"]
```

Either of the options does not work. Could you guide me to fix it?

<img width="402" alt="image" src="https://github.com/user-attachments/assets/0b3d097f-62d1-426a-ac35-b93520db9b00">

MacOS Version 15.0 (24A335)
tmux 3.5a
rioterm 0.2.1

Full config

```toml
# close without confirmation
confirm-before-quit = false

# theme
theme = 'catppuccin-mocha'

hide-mouse-cursor-when-typing = false
option-as-alt = 'rigth'

working-dir = 'None'
# Window padding
padding-x = 16
padding-y = [16, 16]

[editor]
program = 'vi'
args = []

[cursor]
shape = 'block'
blinking = false

[fonts]
family = 'JetBrainsMono Nerd Font'
size = 16.0
hinting = true

[fonts.ui]
family = 'JetBrainsMono Nerd Font'

[shell]
args = ['--login']
program = '/bin/zsh'

[renderer]
performance = 'High'
backend = 'Automatic'
target-fps = 120
strategy = 'events'

[window]
mode = 'Windowed'
opacity = 0.85
blur = true
decorations = 'Buttonless'

[keyboard]
disable-ctlseqs-alt = false

[navigation]
mode = 'Plain'
hide-if-single = true
```
