### ISSUE TITLE
Rio requires editor.args to be given in the config file, even if empty?

### ISSUE THREAD

**Issue by schneiderfelipe** [raphamorim/rio#801]
This crashes:

```toml
[editor]
program = "hx"
# args = []
```

This does not crash:

```toml
[editor]
program = "hx"
args = []
```

Version:

```console
❯ rio --version
rioterm 0.2.1
```
