### ISSUE TITLE
macOS: fallback for missing font glyph?

### ISSUE THREAD

**Issue by raphamorim** [raphamorim/rio#913]
### Discussed in https://github.com/raphamorim/rio/discussions/912

<div type='discussions-op-text'>

<sup>Originally posted by **jeffglover** January 19, 2025</sup>
OS version: macOS Sequoia 15.2
Rio version: 0.2.4 (20230528.115631) & main @ 66257aa23

When using a font missing certain glyphs, in my case braille glyphs mostly used in various progress bars, it does not fall back to another source for those glyphs. This very notable in btop and docker commands. This same config works without issue on Linux.

If I use a font that contains braille glyphs as my primary font, such as cascadiacode or Iosevka this is not an issue.

```toml
[fonts]
size = 16
family = "JetBrainsMono Nerd Font Mono"
```

Non nerd font variants have the same issue: `family = "JetBrains Mono"`

![jetbrains-nfm-btop](https://github.com/user-attachments/assets/8b938fe5-f65f-4a3d-9999-241a232149e2)

---

If I add an extras font with anything that has the missing glyphs, it renders, but does not match the same spacing as the original font.

```toml
[fonts]
size = 16
family = "JetBrainsMono Nerd Font Mono"
extras = [{ family = "Apple Braille" }]
```

Changing extras to another font with braille glyphs such as `IosevkaTerm Nerd Font Mono` renders the glyphs with the same font spacing mismatch.

![jetbrains-nfm-btop-braille](https://github.com/user-attachments/assets/b35cd181-1e33-4244-bb1a-f7139e0a0034)

---

Disclaimer: I'm pretty much exclusively a Linux user for the past 15+ years. I've taken on this Mac for work. My configs were copied over with very little change, where in Linux none of the issues exist. I very well could be missing something.</div>
